export const lofts = [
  {
    id: 1,
    nome: "Golfinho",
    slug: "golfinho",
    codigo: "L2",
    descricao:
      "Este lugar único tem um estilo próprio. O Residencial GercyMar é composto de 6 lofts e linda área de lazer. Está localizado próximo ao Pórtico de saída para o Pontal do Atalaia. Possui cama de casal, ventilador de teto, ar-condicionado e comodidades.",
    capacidade: 2,
    metragem: "35m²",
    preco: "R$ 279,00",
    thumb: "/lofts/golfinho/thumb.jpg",
    fotos: [
      "/lofts/golfinho/foto1.jpg",
      "/lofts/golfinho/foto2.jpg",
      "/lofts/golfinho/foto3.jpg",
      "/lofts/golfinho/foto4.jpg",
    ],
    comodidades: [
      "Wi-Fi de alta velocidade",
      "Ar-condicionado",
      "Smart TV",
      "Cozinha compacta equipada",
      "Cama queen size",
      "Roupa de cama e banho",
      "Varanda exclusiva",
      "Ventilador de teto",
    ],
  },
  {
    id: 2,
    nome: "Conchas",
    slug: "conchas",
    codigo: "L1",
    descricao:
      "Este lugar único tem um estilo próprio. O Residencial GercyMar é composto de 6 lofts e linda área de lazer. Possui varanda exclusiva na frente do Residencial, cama de casal, ventilador de teto e comodidades como: pia, frigobar, micro-ondas, cafeteira.",
    capacidade: 2,
    metragem: "38m²",
    preco: "R$ 289,00",
    thumb: "/lofts/conchas/thumb.jpg",
    fotos: [
      "/lofts/conchas/foto1.jpg",
      "/lofts/conchas/foto2.jpg",
      "/lofts/conchas/foto3.jpg",
      "/lofts/conchas/foto4.jpg",
    ],
    comodidades: [
      "Wi-Fi de alta velocidade",
      "Ar-condicionado",
      "Smart TV",
      "Frigobar",
      "Micro-ondas",
      "Cafeteira",
      "Cama queen size",
      "Ventilador de teto",
      "Varanda exclusiva",
    ],
  },
  {
    id: 3,
    nome: "Corais",
    slug: "corais",
    codigo: "L5",
    descricao:
      "Loft com varanda exclusiva na lateral do Residencial, cama de casal, ventilador de teto e comodidades como: pia, frigobar, micro-ondas, cafeteira. O refúgio perfeito para recarregar as energias e planejar a próxima aventura em Arraial do Cabo.",
    capacidade: 2,
    metragem: "36m²",
    preco: "R$ 279,00",
    thumb: "/lofts/corais/thumb.jpg",
    fotos: [
      "/lofts/corais/foto1.jpg",
      "/lofts/corais/foto2.jpg",
      "/lofts/corais/foto3.jpg",
      "/lofts/corais/foto4.jpg",
    ],
    comodidades: [
      "Wi-Fi de alta velocidade",
      "Ar-condicionado",
      "Smart TV",
      "Frigobar",
      "Micro-ondas",
      "Cafeteira",
      "Cama queen size",
      "Roupa de cama e banho",
      "Varanda exclusiva lateral",
    ],
  },
  {
    id: 4,
    nome: "Dunas",
    slug: "dunas",
    codigo: "L4",
    descricao:
      "Possui varanda e uma varanda exclusiva na frente do Residencial, cama de casal, uma cama auxiliar de solteiro, ventilador de teto, ar-condicionado e comodidades. Ideal para quem busca conforto e localização privilegiada em Arraial do Cabo.",
    capacidade: 3,
    metragem: "40m²",
    preco: "R$ 299,00",
    thumb: "/lofts/dunas/thumb.jpg",
    fotos: [
      "/lofts/dunas/foto1.jpg",
      "/lofts/dunas/foto2.jpg",
      "/lofts/dunas/foto3.jpg",
      "/lofts/dunas/foto4.jpg",
    ],
    comodidades: [
      "Wi-Fi de alta velocidade",
      "Ar-condicionado",
      "Smart TV",
      "Cozinha compacta equipada",
      "Cama queen size + cama auxiliar",
      "Roupa de cama e banho",
      "Varanda exclusiva frontal",
      "Ventilador de teto",
    ],
  },
  {
    id: 5,
    nome: "Estrela do Mar",
    slug: "estrela-do-mar",
    codigo: "L3",
    descricao:
      "Este lugar único tem um estilo próprio. O Residencial GercyMar é composto de 6 lofts. Possui varanda exclusiva na frente do Residencial, cama de casal, ventilador de teto e comodidades como: pia, frigobar, micro-ondas, cafeteira.",
    capacidade: 2,
    metragem: "36m²",
    preco: "R$ 289,00",
    thumb: "/lofts/estrela-do-mar/thumb.jpg",
    fotos: [
      "/lofts/estrela-do-mar/foto1.jpg",
      "/lofts/estrela-do-mar/foto2.jpg",
      "/lofts/estrela-do-mar/foto3.jpg",
      "/lofts/estrela-do-mar/foto4.jpg",
    ],
    comodidades: [
      "Wi-Fi de alta velocidade",
      "Ar-condicionado",
      "Smart TV",
      "Frigobar",
      "Micro-ondas",
      "Cafeteira",
      "Cama queen size",
      "Roupa de cama e banho",
      "Varanda exclusiva frontal",
    ],
  },
  {
    id: 6,
    nome: "Jubarte",
    slug: "jubarte",
    codigo: "L6",
    descricao:
      "O maior loft do complexo, o Jubarte oferece muito espaço e conforto. Com decoração sofisticada, área de estar ampla e todas as comodidades para uma estadia perfeita no paraíso de Arraial do Cabo.",
    capacidade: 4,
    metragem: "45m²",
    preco: "R$ 349,00",
    thumb: "/lofts/jubarte/thumb.jpg",
    fotos: [
      "/lofts/jubarte/foto1.jpg",
      "/lofts/jubarte/foto2.jpg",
      "/lofts/jubarte/foto3.jpg",
      "/lofts/jubarte/foto4.jpg",
    ],
    comodidades: [
      "Wi-Fi de alta velocidade",
      "Ar-condicionado",
      "Smart TV",
      "Cozinha completa equipada",
      "Cama queen size + sofá-cama",
      "Roupa de cama e banho",
      "Varanda ampla",
      "Ventilador de teto",
      "Espaço de trabalho",
    ],
  },
];

export const getLoftBySlug = (slug: string) => {
  return lofts.find((loft) => loft.slug === slug);
};
